name: UltimateTags
version: ${project.version}
main: io.github.henrique02w.ultimatetags.UltimateTagsPlugin
api-version: "26.2"
folia-supported: false
authors:
  - Henrique02W
website: https://github.com/Henrique02W/UltimateTags
description: Modern Adventure/MiniMessage tag system for Paper servers.
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    TAB:
      load: BEFORE
      required: false
      join-classpath: false
    nChat:
      load: BEFORE
      required: false
      join-classpath: false
permissions:
  ultimatetags.admin:
    default: op
  ultimatetags.use:
    default: true
